[package]
name = "memo-app"
version.workspace = true
edition.workspace = true

[dependencies]
memo-core = { workspace = true }
memo-sync = { workspace = true }
eframe = { workspace = true }
anyhow = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
# 钉住传递依赖，阻止 Cargo 拉 edition2024 包
url = { workspace = true }
idna = { workspace = true }
base64ct = { workspace = true }
password-hash = { workspace = true }
getrandom = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_UI_Controls_Dialogs",
] }
